### ISSUE TITLE
Core Endpoint - Auth

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/server#4]
This is handled by ORY authentication backends to provide authentication for us.

### TODO

- [ ] Add initial ORY Auth endpoints
- [ ] Access Control via scopes implementation
- [ ] implement Access Control for Playtesting (probably scope-based).

**Comment by martmists** [comment]
Currently implemented through PostgreSQL instead of ORY.
